/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useState } from "react";
import { useEffect } from "react";
export default function GltfLoader(props) {
  const group = useRef();
  const [hovered, setHovered] = useState(false);
  const [selected, setSelected] = useState(false);
  const [selectedObject, setSelectedObject] = useState(null);
  useEffect(() => void (document.body.style.cursor = hovered ? "pointer" : "auto"), [hovered])
  const { nodes, materials } = useGLTF("/models/MathClass_V3.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cuboid_Hitbox.geometry}
        material={nodes.Cuboid_Hitbox.material}
        onPointerOver={(e) => setHovered(true)}
        onPointerOut={(e) => setHovered(false)}
        onPointerDown={(e) => { setSelected(true); setSelectedObject(e.object); console.log(e.object) }}
        position={[0.67, 1.82, 2.99]}
        
        
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder_Hitbox.geometry}
        material={nodes.Cylinder_Hitbox.material}
        onPointerOver={(e) => setHovered(true)}
        onPointerOut={(e) => setHovered(false)}
        onPointerDown={(e) => { setSelected(true); setSelectedObject(e.object); console.log(e.object) }}
        position={[-0.77, 1.24, 2.99]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Parallelepiped_Hitbox.geometry}
        material={nodes.Parallelepiped_Hitbox.material}
        position={[-0.78, 1.81, 2.99]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box_Hitbox.geometry}
        material={nodes.Box_Hitbox.material}
        position={[-0.06, 1.81, 2.99]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pyramid_Hitbox.geometry}
        material={nodes.Pyramid_Hitbox.material}
        position={[0.67, 1.26, 2.99]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curtains.geometry}
        material={materials.Curtains}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Blackboard.geometry}
        material={materials["Material.008"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Environment.geometry}
        material={materials.Material}
        position={[0, -1.54, 0]}
        rotation={[0, 0.05, 0]}
        scale={139.2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MathRoom.geometry}
        material={materials.Room}
      />
      
    </group>
    
  );
}

useGLTF.preload("/models/MathClass_V3.gltf");
