/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function GltfLoader(props) {
    const group = useRef()
    useGLTF.preload('/home.gltf')
    const { nodes, materials } = useGLTF('/models/home.gltf')
    return (
        <group ref={group} {...props} dispose={null}>
            <group>
                <group
                    position={[0, -0.5, 0]}
                    scale={0.05}
                    rotation={[Math.PI / 2, 0, 0]}
                >
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Scene014.geometry}
                        material={materials.TheMaterial}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Scene014_1.geometry}
                        material={materials.Glass}
                    />
                </group>
            </group>
        </group>
    )
}
